#!/bin/bash

set -e

# Modules
for ext in \
  muuntaja \
  muuntaja-form \
  muuntaja-cheshire \
  muuntaja-charred \
  muuntaja-msgpack \
  muuntaja-yaml; do
  cd modules/$ext; lein "$@"; cd ../..;
done
