#!/bin/zsh

ext="sedbak$$"

find . -name project.clj -exec sed -i.$ext "s/\[\(\(fi\.\)\?metosin\/muuntaja.*\) \".*\"\]/[\1 \"$1\"\]/g" '{}' \;
find . -name project.clj -exec sed -i.$ext "s/defproject \(\(fi\.\)\?metosin\/muuntaja.*\) \".*\"/defproject \1 \"$1\"/g" '{}' \;
sed -i.$ext "s/\[\(\(fi\.\)\?metosin\/muuntaja.*\) \".*\"\]/[\1 \"$1\"\]/g" **/*.md
find . -name "*.$ext" -exec rm '{}' \;
